#===========Directories=========
BIN_DIR     =bin
BUILD_DIR   =build
SRC_DIR     =src
INCLUDE_DIR =$(SRC_DIR)/include
SITE_DIR    =site
TMP_DIR     =tmp

#===========Building============

CC      =gcc
LD      =gcc
DBG     =gdb

#==========Compile flags========

LOG      ?=NOLOG #use LOG=DEBUG to compile in debug mode

CFLAGS   =-std=c11
CFLAGS   +=-c
CFLAGS   +=-I.
CFLAGS   +=-I$(INCLUDE_DIR)
CFLAGS   +=$(DEBUG)
CFLAGS   +=-D$(LOG)
CFLAGS   +=-pthread
CFLAGS   +=-w

RFLAGS   =o3 #Release flags

#==========Link flags===========

LFLAGS   =-std=c11
LFLAGS   +=-I.
LFLAGS   +=-I$(INCLUDE_DIR)
LFLAGS   +=-pthread 
LFLAGS   +=$(DEBUG)
LFLAGS   +=-D$(LOG)

LFLAGS   += -static-libgcc -w
LFLAGS   += -static-libasan  -static-libtsan  -static-liblsan
LFLAGS   +=-static-libubsan -static-libmpx  -static-libmpxwrappers 
LFLAGS   +=-shared-libgcc

#==========Debug flags==========

DBGFLAGS = -q


#==========Other settings=======
OUTPUT  ?=$(TMP_DIR)/tmp